# Copyright (c) 2023-2024 Antmicro <www.antmicro.com>
#
# SPDX-License-Identifier: Apache-2.0

manifest:
  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos

    - name: apache
      url-base: https://github.com/apache

    - name: dmlc
      url-base: https://github.com/dmlc

    - name: iree-org
      url-base: https://github.com/iree-org

  projects:
    - name: zephyr
      remote: zephyrproject-rtos
      revision: b9bfff29f4bf99ecb19dd2078bd06447e279cfcf
      import:
        path-allowlist:
          - modules/debug/*
          - modules/hal/*
          - modules/lib/*
          - modules/tee/tf-m/*

    - name: tflite-micro
      remote: zephyrproject-rtos
      revision: zephyr-v4.1.0

    - name: tvm
      remote: apache
      revision: v0.18.0

    - name: dlpack
      remote: dmlc
      revision: main

    - name: iree
      remote: iree-org
      revision: 2f40854c548cbe082190d1dd1691a342ffd9006b
      submodules:
        - path: third_party/flatcc
