# Copyright (c) 2026 Antmicro <www.antmicro.com>
#
# SPDX-License-Identifier: Apache-2.0

CONFIG_ZPL=y
CONFIG_ZPL_TRACE=y
CONFIG_ZPL_TRACE_FORMAT_CTF=y
CONFIG_ZPL_INFERENCE_PROFILING=y

CONFIG_ZPL_MEMORY_PROFILING=y
CONFIG_ZPL_MEMORY_PROFILING_INTERVAL=100
CONFIG_ZPL_MEMORY_PROFILING_THREAD_PRIORITY=-1

CONFIG_ZPL_CPU_LOAD_TRACE=y
CONFIG_ZPL_CPU_LOAD_PROFILING=y
CONFIG_ZPL_CPU_LOAD_PROFILING_INTERVAL=100
CONFIG_ZPL_CPU_LOAD_PROFILING_THREAD_PRIORITY=-1

CONFIG_CPU_LOAD=y
CONFIG_SYS_HEAP_ARRAY_SIZE=4
CONFIG_COMMON_LIBC_MALLOC=y

CONFIG_ZPL_SCOPE_MARKING=y
CONFIG_TRACING_SYNC=y
CONFIG_ZPL_TRACE_FULL_MODE=y

# There is a lot of mutex and interrupt events during inference, related to Zephyr RTOS inner
# workings - these are not really relevant to ML model tracing, so we turn them off.
CONFIG_TRACING_MUTEX=n
CONFIG_TRACING_ISR=n

# Additional tracing events, that show inner workings of Kenning Zephyr Runtime
# - can be turned off to trace the model only
CONFIG_KENNING_ZEPHELIN_TRACE_FRAMEWORK=y
CONFIG_KENNING_ZEPHELIN_TRACE_RUNTIME=y
CONFIG_KENNING_ZEPHELIN_TRACE_REQUESTS=y
CONFIG_KENNING_ZEPHELIN_TRACE_MODEL=y
CONFIG_KENNING_ZEPHELIN_TRACE_SERVER=y
CONFIG_KENNING_ZEPHELIN_TRACE_INFERENCE_SESSION=y
CONFIG_KENNING_ZEPHELIN_TRACE_LOGGING=y
