# Copyright (c) 2026 Antmicro <www.antmicro.com>
#
# SPDX-License-Identifier: Apache-2.0

CONFIG_ZPL=y
CONFIG_ZPL_TRACE=y
CONFIG_ZPL_TRACE_FORMAT_CTF=y
CONFIG_ZPL_INFERENCE_PROFILING=y

CONFIG_ZPL_MEMORY_PROFILING=y
CONFIG_ZPL_MEMORY_PROFILING_INTERVAL=100
CONFIG_ZPL_MEMORY_PROFILING_THREAD_PRIORITY=-1

CONFIG_ZPL_CPU_LOAD_TRACE=y
CONFIG_ZPL_CPU_LOAD_PROFILING=y
CONFIG_ZPL_CPU_LOAD_PROFILING_INTERVAL=100
CONFIG_ZPL_CPU_LOAD_PROFILING_THREAD_PRIORITY=-1

CONFIG_CPU_LOAD=y
CONFIG_SYS_HEAP_ARRAY_SIZE=4
CONFIG_COMMON_LIBC_MALLOC=y

CONFIG_TRACING_SYNC=y

CONFIG_ZPL_TRACE_FULL_MODE=y
