# Copyright (c) 2025 Antmicro <www.antmicro.com>
#
# SPDX-License-Identifier: Apache-2.0

CONFIG_ZPL_TRACE_BACKEND_KENNING_PROTOCOL=y

# Kenning Protocol Trace Backend is more resource-intensive, that other backends.
CONFIG_ZPL_CPU_LOAD_PROFILING_THREAD_STACK_SIZE=1024
CONFIG_ZPL_MEMORY_PROFILING_THREAD_STACK_SIZE=1024

# We have to choose some pre-existing Zephelin backend (Zephelin does not allow
# a null value) that will not interfere with out custom backend.
CONFIG_ZPL_TRACE_BACKEND_DEBUGGER=y
