/*
 * Copyright (c) 2023-2024 Antmicro <www.antmicro.com>
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#include <tensorflow/lite/micro/micro_mutable_op_resolver.h>

#include "resolver.h"

tflite::MicroMutableOpResolver<TFLITE_RESOLVER_SIZE> tflite_resolver;

void tflite_initialize_resolver()
{
    tflite_resolver.AddAbs();
    tflite_resolver.AddAdd();
    tflite_resolver.AddAddN();
    tflite_resolver.AddArgMax();
    tflite_resolver.AddArgMin();
    tflite_resolver.AddAssignVariable();
    tflite_resolver.AddAveragePool2D();
    tflite_resolver.AddBatchToSpaceNd();
    tflite_resolver.AddBroadcastArgs();
    tflite_resolver.AddBroadcastTo();
    tflite_resolver.AddCallOnce();
    tflite_resolver.AddCast();
    tflite_resolver.AddCeil();
    tflite_resolver.AddCircularBuffer();
    tflite_resolver.AddConcatenation();
    tflite_resolver.AddConv2D();
    tflite_resolver.AddCos();
    tflite_resolver.AddCumSum();
    tflite_resolver.AddDepthToSpace();
    tflite_resolver.AddDepthwiseConv2D();
    tflite_resolver.AddDequantize();
    tflite_resolver.AddDetectionPostprocess();
    tflite_resolver.AddDiv();
    tflite_resolver.AddElu();
    tflite_resolver.AddEqual();
    tflite_resolver.AddEthosU();
    tflite_resolver.AddExp();
    tflite_resolver.AddExpandDims();
    tflite_resolver.AddFill();
    tflite_resolver.AddFloor();
    tflite_resolver.AddFloorDiv();
    tflite_resolver.AddFloorMod();
    tflite_resolver.AddFullyConnected();
    tflite_resolver.AddGather();
    tflite_resolver.AddGatherNd();
    tflite_resolver.AddGreater();
    tflite_resolver.AddGreaterEqual();
    tflite_resolver.AddHardSwish();
    tflite_resolver.AddIf();
    tflite_resolver.AddL2Normalization();
    tflite_resolver.AddL2Pool2D();
    tflite_resolver.AddLeakyRelu();
    tflite_resolver.AddLess();
    tflite_resolver.AddLessEqual();
    tflite_resolver.AddLog();
    tflite_resolver.AddLogSoftmax();
    tflite_resolver.AddLogicalAnd();
    tflite_resolver.AddLogicalNot();
    tflite_resolver.AddLogicalOr();
    tflite_resolver.AddLogistic();
    tflite_resolver.AddMaxPool2D();
    tflite_resolver.AddMaximum();
    tflite_resolver.AddMean();
    tflite_resolver.AddMinimum();
    tflite_resolver.AddMirrorPad();
    tflite_resolver.AddMul();
    tflite_resolver.AddNeg();
    tflite_resolver.AddNotEqual();
    tflite_resolver.AddPack();
    tflite_resolver.AddPad();
    tflite_resolver.AddPadV2();
    tflite_resolver.AddPrelu();
    tflite_resolver.AddQuantize();
    tflite_resolver.AddReadVariable();
    tflite_resolver.AddReduceMax();
    tflite_resolver.AddRelu();
    tflite_resolver.AddRelu6();
    tflite_resolver.AddReshape();
    tflite_resolver.AddResizeBilinear();
    tflite_resolver.AddResizeNearestNeighbor();
    tflite_resolver.AddRfft();
    tflite_resolver.AddRound();
    tflite_resolver.AddRsqrt();
    tflite_resolver.AddSelectV2();
    tflite_resolver.AddShape();
    tflite_resolver.AddSin();
    tflite_resolver.AddSlice();
    tflite_resolver.AddSoftmax();
    tflite_resolver.AddSpaceToBatchNd();
    tflite_resolver.AddSpaceToDepth();
    tflite_resolver.AddSplit();
    tflite_resolver.AddSplitV();
    tflite_resolver.AddSqrt();
    tflite_resolver.AddSquare();
    tflite_resolver.AddSquaredDifference();
    tflite_resolver.AddSqueeze();
    tflite_resolver.AddStridedSlice();
    tflite_resolver.AddSub();
    tflite_resolver.AddSum();
    tflite_resolver.AddSvdf();
    tflite_resolver.AddTanh();
    tflite_resolver.AddTranspose();
    tflite_resolver.AddTransposeConv();
    tflite_resolver.AddUnidirectionalSequenceLSTM();
    tflite_resolver.AddUnpack();
    tflite_resolver.AddVarHandle();
    tflite_resolver.AddWhile();
    tflite_resolver.AddWindow();
    tflite_resolver.AddZerosLike();
}
